name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install MCDReforged
      run: |
        python -m pip install --upgrade pip
        pip install mcdreforged
    - name: Pack with MCDReforged
      run: |
        cd src
        for pack in ./*
        do
        if test -d $pack
        then
        cd $pack
        mcdreforged pack
        mv ./*.mcdr ../
        cd ..
        fi
        done

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MCDR Package
        path: |
          src/*.mcdr
